### ISSUE TITLE
Bluetooth Paired not connected- control not working 

### ISSUE THREAD

**Issue by bimalnair** [carlosrafaelgn/FPlayArduino#1]
Hi,
  I have followed the instruction, uploaded arduino code  and the Bluetooth is paired with the Phone, but how can we make it connect it with the arduino from the player. I have tried some terminal application and its connecting and I am receiving data from arduino when I click buttons.

**Comment by bimalnair** [comment]
Found how to connect the BT by going to menu, visualiser, BT+ Arduino and connect . But still the BT controls are not working, what could be the issue

**Comment by carlosrafaelgn** [comment]
Hi there!
I have not paid too much attention to that specific feature in a while. Probably, there must be something wrong with FPlay's code. I will try and check it over. Thanks for warning me!

**Comment by carlosrafaelgn** [comment]
Hi again!
I have updated FPlay (v1.67) and I have also added a Windows test project (in C#/Windows Forms).
Everything working fine!
Regards!
